### ISSUE TITLE
Code coverage via Symphony client

### ISSUE THREAD

**Issue by vitalyiegorov** [imbo/behat-api-extension#72]
@christeredvartsen We have faced a situation where we would like to get code coverage by running web api tests. I believe that this is possible if we can change Guzzle client to [Symfony Client](http://symfony.com/doc/current/testing.html#functional-tests). Do you know any ClientInterface implementation for this? Our we can make our own? What do you think?

**Comment by christeredvartsen** [comment]
Are you running tests against the PHP httpd, or some other web server? I'm collecting code coverage through the internal PHP httpd through a custom router and some HTTP headers set in the Guzzle client. I can share the setup if you want?

**Comment by vitalyiegorov** [comment]
We have apache setup, can you please share your config?

**Comment by christeredvartsen** [comment]
Created a gist with the relevant parts here:

https://gist.github.com/christeredvartsen/de3123c0c5cba1519ab57cd3e3e5a665

The `router.php` file needs to handled somewhat different since you use Apache, but you could probably just include it in your bootstrap file when in debug/dev mode or something similar.

The gist also includes a configuration file that enables code coverage, so when I want to collect coverage I can just use that file:

    ./vendor/bin/behat -c behat-coverage.yml

With this setup you won't need to change the Behat API extension at all.

**Comment by christeredvartsen** [comment]
@vitalyiegorov Did you get code coverage up and running?

**Comment by christeredvartsen** [comment]
:zzz:
